Add top level error logging.
Xjph/ObservatoryCore pull request #55
Opened 2022-02-20 19:52 UTC by Xjph

2022-02-21 22:33 UTC, fredjk-gh requested changes
Only requesting changes because the test exception is left in there. I assume we don't want that committed.

2022-02-21 22:33 UTC, fredjk-gh commented on ObservatoryCore/ObservatoryCore.cs
> +                throw new Exception("Test Exception", new Exception("Inner Exception Test"));
Should this still be here?

2022-02-21 22:33 UTC, fredjk-gh commented on ObservatoryCore/ObservatoryCore.cs
> +                errorMessage.AppendLine($"Error encountered in Elite Observatory {version}.");
Optional: Consider chaining:

errorMessage
    .AppendLine(...)
    .AppendLine(...)
    .AppendLine();

(Of course, however the editor formats it. Below as well.)

2022-02-22 13:09 UTC, Xjph commented on ObservatoryCore/ObservatoryCore.cs
> +                throw new Exception("Test Exception", new Exception("Inner Exception Test"));
Definitely shouldn't!

2022-02-22 16:59 UTC, fredjk-gh approved these changes

2022-02-22 17:00 UTC, merged